fieldLayouts:
  8c3d281d-b43b-4ce0-9e71-dc7786428f3d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: journal
hasUrls: true
name: Journal
settings:
  path: '@assetsBasePath/journal'
sortOrder: 3
type: craft\volumes\Local
url: '@assetsBaseUrl/journal'
