contentColumnType: text
fieldGroup: 7ccd7585-e576-4a7c-81bd-999c168264e2
handle: customCss
instructions: 'Custom CSS for Featured pages'
name: 'Custom CSS'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '8'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
