contentColumnType: text
fieldGroup: f499a594-9217-49ea-b1dc-1893b0561026
handle: seoTitle
instructions: ''
name: 'SEO Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
