contentColumnType: string
fieldGroup: 7ccd7585-e576-4a7c-81bd-999c168264e2
handle: tags
instructions: null
name: Tags
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  limit: null
  localizeRelations: false
  selectionLabel: null
  showSiteMenu: true
  source: 'taggroup:3b5be951-85be-446f-8974-c6e4cbe515c5'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
