enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  0b61de0c-3eaf-46f8-a16d-d22ea8a17a00:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
